### ISSUE TITLE
Add format.sty to repo?

### ISSUE THREAD

**Issue by stephenturner** [weecology/data-sharing-paper#70]
I only recently started seriously investigating using Markdown to write scientific articles. I see a `format.sty` file in the `pandoc` command in the makefile, but this file isn't in the repo. Can you add this so I can better understand how pandoc renders the .md to .pdf? Thanks.

**Comment by dmcglinn** [comment]
Hey Stephen,  I believe this is a file that Ethan has on his local machine and unfortunately he will be out of email range until May 31st. Once he gets back I'm sure he'll upload it. Just wanted to give you the heads up.
Dan

**Comment by stephenturner** [comment]
Great, thanks Dan.

**Comment by karthik** [comment]
@stephenturner Anything in particular you're looking for? Line numbers, double spacing, margins? Just need to replicate Ethan's formatting? Maybe I can help.

**Comment by stephenturner** [comment]
New to pandoc, just wanted to see what an example .sty file would look like.

**Comment by karthik** [comment]
It's just standard `LateX` styling. Mine usually just contains margins ([e.g.](https://github.com/karthikram/smb_git/blob/master/margins.sty)) but sometimes I also add line numbers and spacing.  

For margins

```
\usepackage[vmargin=1in,hmargin=1in]{geometry}
```

For double spacing

```
\usepackage{setspace}
\doublespacing
```

Line numbers

```
\usepackage{lineno}
\linenumbers
```

Number every other line

```
\usepackage{lineno}
\linenumbers
\modulolinenumbers[2]
```

**Comment by ethanwhite** [comment]
Oops, sorry. There I go setting a bad example by forgetting to commit. It's up now.

**Comment by stephenturner** [comment]
thank you!
