### ISSUE TITLE
Reviewer Comments

### ISSUE THREAD

**Issue by cboettig** [weecology/data-sharing-paper#71]
Hi Ethan and co-authors,

I enjoyed reviewing your paper and assume by now you have received my comments from the Journal office.  In the spirit of your open writing of this manuscript I thought I would also paste my review here.  I have received approval from the journal office to do so.  

I've taken the liberty of linking this issue in a comment from the PeerJ preprint. As the PeerJ comments are limited to 1500 characters, it is not the most useful platform to give more substantive feedback anyway.  Great work and a pleasure to review.  

Sincerely,

Carl Boettiger

---

I have read with great interest the manuscript, "Nine simple ways to make it easier to (re)use your data", and I am happy to recommend it for publication. I do have a few more minor concerns I hope the authors will consider -- in particular regarding the discussion of metadata in recommendation 2. Detailed comments below.   
- [ ] **1. "Share your data"**

Motivate the data sharing more directly for the reader -- who benefits from these practices? (e.g. highlight individal benefits, community benefits may be more self-evident)

All references you cite identify a cultural challange as dominant.  While addressing that is not really the scope / objective here, it would be worth acknowledging this.   Recommendation #1 kind of addresses this, but cannot really do justice to it in two paragraphs.  The paper will serve as a practical guide to those intersted in doing so, rather than convincing those that have doubts.

That said, the topic sentence at line 50 probably shouldn't be "scientists are reluctant to share..", but something to the effect that incentives have previously been insufficient to encourage sharing but are rapidly shifting.  

L50 - 64 The structure of the arguments jump around a bit in this paragraph.  I'd recommend something like "1. advantages/ reasons to share", "2. reasons scientists don't share so much yet" and "3. changes".   You provide mention of changes in funding requirements and laws, only to switch back to the "reluctant to share".  

L. 49. Great set of links.  In addition to FASTR, maybe link the recent whitehouse statement that would mandate this as well?  Also, not sure what the journal policies are for linking vs formally citing this material.  

Lines 33:34 Jones et al are good references, but broader than the evidence for not following 'best-practices'.  Consider these citations     
- Palmer M, Bernhardt ES, Chornesky EA, Collins SL, Dobson AP, et al. 2005. Eco- logical science and sustainability for the 21st century. Front. Ecol. Environ. 3:4–11

You cite this later, but might be appropriate to mention it here;
- Parr CS, Cummings MP. 2005. Data sharing in ecology and evolution. Trends Ecol. Evol. 20(7):362–63
- [ ] **2. Metadata**

L 82-84. Like much other advice, you casually throw out names of "metadata standards", some of which are defined as XML Schema, some of which are vocabularies or proper ontologies, etc., along side vague recommendations to "describe the data". My intuition is that the average ecologist reading this will go through these recommendations like this:

1) Describe the "What, when, where, how of the  data" -- oh, that'll be in the published paper. 
2) "How to access the data" email me, duh.  I'm the corresponding author.  It says so on the paper.  
3) "Suitability of the data in answering other questions" Stuff I'll probably discuss in the introduction. If you don't know what it's suitable for, you probably shouldn't be using my data anyhow.  
4) "Warnings about known problems" You kidding me?  My data does not have problems or inconsistencies!
5) "Information to confirm that the data is properly imported, like the number of rows and columns".  Ah ha!  What a good idea, I'll list the number of rows and columns of my data and I'll be cutting edge. 

If we are serious about improving ecological metadata, I think we need something more persuasive about how it can add value and to whom.  The current manuscript makes no attempt to explain the value of machine readable standards (even merely to point out they are machine-readable).  Yes, you point to three excellent tools which helping to lower the technical barrier, but not the social / motivational barriers. 

Also, there's a lot of overlap here with the issues in #4 "Standard data formats", but the link is not made clear.  
- [ ] **3. Unprocessed form of data**

I love this section.  Just the other day I was so happy to see that this fascinating research I was reading had public data, and so dismayed to see that the raw time series I needed were not available.  You might want some discussion of just what "raw data" means -- one person's raw data is another's highly processed data.  
- [ ] **4. Standard data formats**

Great section, with nice concrete recommendations that can easily be understood and implemented by anyone.  

My only gripe is that a lot of the issues discussed here are addressed by the metadata standards you cite earlier, but the connection is completely ignored and probably lost on most readers.  

Section 5 really feels like a subsection of 4.3 "standard formats within cells", but given the importance of the issue I'm happy to see it remain it's own section. 
- [ ] **6.  Combining with other data sets**

A good section in principle, but not very concrete.  It sounds like your primary advice here is to avoid undefined abbreviations, and to include columns with generic information like species or lat/long coordinates that might be useful to others. In both cases, you appear to be citing issues that have more to do with metadata.  E.g. if I collect all my data on a single species at a single geographic site; is it really necessary that I add columns for species and lat-long, rather than define this information in the metadata?

I think more helpful here would be to emphasize the value of collecting/recording additional generic data even if it is not relevant for your study. (Researchers not interested in spatial or seasonal patterns do not always report spatial coordinates or sampling dates and times, temperature/weather information, gross measurements of sampled individuals like length and mass etc.)  
- [ ] **7. Quality control**

Very good section, but you ignore any mention of tools that can assist with at least some of these things, from the very basic (e.g. reading the file into software such as R and performing basic visual inspection / graphing to make sure it is imported) to richer options possible with stricter formats (XML schema validation, etc.). 
- [ ] **8.  Repositories**

Great section. Emphasize the personal advantages here?  Perhaps with references that have demonstrated the personal benefits (citation, ease of re-use / avoiding file loss, etc.)

Could you consider mentioning archiving things like an R script that is used to clean / manipulate the raw data to prepare it for analysis as well?  
- [ ] **9.  Licensing**

You might mention established recommendations such as http://pantonprinciples.org/

It might also be worth calling attention to the fact that there is a substantial question of whether your data can indeed be protected by copyright at all and protected by certain copyright licenses. (e.g. while it may be tempting to a researcher to apply a cc-by-nc license to their data, that license is intended for "creative works" and may not cover what may instead be a collection of facts. Some further references to this issue might also help).  
- [ ] **Conclusion**

Very good, glad that it returns to the theme of personal benefits to following these recommendations.  (saving time, facilitating collaboration, new possibilities for research), but I think you could say more on that theme. How about "looks good on NSF data management proposal" or any other grant application, or increased citation advantage (Piwowar's work). 

Maybe add a few concrete suggestions on where to start (perhaps creating a data standard for your lab)

**Comment by ethanwhite** [comment]
Split out into separate issues (#92 - #102).

**Comment by dmcglinn** [comment]
@cboettig thank you for the great feedback on our manuscript and for sharing your review in the open!  With respect to your comment on the data formatting, "... a lot of the issues discussed here [data formatting section 4] are addressed by the metadata standards ...." could you please point us to a reference or an example link were a metadata standard documents these kinds of data formatting suggestions. Thank you for pointing this out to us.

**Comment by cboettig** [comment]
@dmcglinn Thanks for the follow-up question, I agree I was rather vague. 

Everything in this section is valuable and needs to be spelled out just the way you do it, so great job. My observation was the entire section is written more-or-less assuming that the data is essentially a csv file or similar custom table that is not beholden to a specific schema such as EML. I really no expert on EML or most of the other "Metadata Standards" you list in lines 80-88.  As I mention in my critique of that section, some of those are just simple ontologies (e.g. Dublin Core) that help a machine decide which date is the publication date, but some are "schemas" that are designed to address the exact issues you discuss here and elsewhere in the paper: 

File format, table format, and within-cell formatting (e.g. the character set used, the delimiters used, the formatting for dates, etc). On one hand, I recognize the reality that most researchers work with excel/csv files and that this is targeted to them. On the other, I can't help but imagine that the folks who have helped design schemas that address these challenges will only smack their head at this. An EML file (e.g. excerpt from [this one](http://harvardforest.fas.harvard.edu/sites/harvardforest.fas.harvard.edu/files/data/eml/hf205.xml)) can declare it's date-time format, e.g. 

``` xml
<attribute id="1354213311471">
<attributeName>year</attributeName>
<attributeDefinition>year, 2012</attributeDefinition>
<measurementScale>
<dateTime>
<formatString>YYYY</formatString>
</dateTime>
</measurementScale>
</attribute>
<attribute id="1354213311472">
<attributeName>day</attributeName>
<attributeDefinition>Julian day. Range: 170 – 209.</attributeDefinition>
<measurementScale>
<dateTime>
<formatString>DDD</formatString>
</dateTime>
</measurementScale>
</attribute>
<attribute id="1354213311473">
<attributeName>hour.min</attributeName>
<attributeDefinition>hour and minute of observation. Range 1 – 2400 (integer)</attributeDefinition>
<measurementScale>
<dateTime>
<formatString>hhmm</formatString>
</dateTime>
</measurementScale>
</attribute>
```

(It may be worth noting that all the terms like measurementScale come with precisely defined meanings in the EML namespace),  One might also call attention to the advantages of an explicitly machine readable and verifiable format in place of a convention (can I just assume some random csv file I pull from Dryad uses ISO8601 dates?)  

The bigger picture issue I had is this: no one is going to adopt these more useful structured data standards without any convincing idea of what value they add. Here you have a good opportunity to point out things like: you could worry about whether you have a non-ascii character or a funny delimiter or your date is in the right format and a million other things each time, or you could learn a tool that could take care of all this for you and much much more!  Perhaps at least a few sentences to that effect at the end of this section might be useful, if not a concrete example.

Full disclosure here: Like I said, I don't know the EML standard well, having not had the opportunity to work with much data already in EML format. When I started writing this, I didn't know how it defined dates, if it even had a mechanism. But my rudimentary understanding of the purpose of having an XML schema for metadata cries out that the whole point is to solve these kinds of things, so I could bet on finding an example. I mention this only by way of pointing out that it's not necessary to learn the whole schema, just understanding a bit of the logic helps us find the use cases as we need them.  

Someone more familiar with this stuff could probably provide much better examples; but we don't just need more experts, we need more bridges between experts and users.  I think this paper can be a brilliant bridge.

**Comment by ethanwhite** [comment]
@cboettig Thanks for the additional feedback.

We all agree with you about the value of standards and machine readable metadata. Broad implementation of these would revolutionize the field by allowing us to meaningfully access the long-tail of ecological data and it would certainly make research for us personally much easier. However, following lengthy conversations during the planning, writing, and revision of the ms we disagree that a more in-depth discussion of these belongs in this current paper because at this point working with standards and XML are in no way "simple" for most ecologists.  In other words, we think that it is 2nd or 3rd level material, whereas we are trying to reach the 1st level audience. 

This paper is intentionally targeted as a very basic introduction to good data practices for folks who have largely no background in this area. We have attempted to clarify this point in response to #84. This is why we have focused on points that are easy to understand even if you are only working with your own data. These are the folks who are increasingly posting lots of valuable data to places like figshare and Dryad, but in forms that are very difficult to work with even a single dataset at a time. We interact with lots of these folks on a regular basis as part of a variety of educational initiatives and it is our belief (and in several cases actual experience) that attempting to introduce these concepts during a basic introduction is way too much. One might argue that it can't hurt to provide additional information in the paper, after all the readers can simply ignore it, but in our experience introducing too much computational/quantitative information at once to scientists results in greater aversion and a decrease likelihood of adoption even the more basic material. As such, we intentionally chose to avoid going into more detail in these areas.

That said, we absolutely think that this is a really important topic and something that needs to be better explained both in terms of how and why. We would love to see a "Five somewhat more complicated ways to make it easier to (re)use your data" paper that addresses this next level of complexity.

**Comment by ethanwhite** [comment]
@cboettig Having said all of this I have now tried to expand the metadata section just a bit to try to emphasize the value of this in #122.

**Comment by cboettig** [comment]
I like the new sentence in section 2.  It would be misleading to simply
tell the readers "you can use a metadata standard" without mentioning them
again or warning them what they are getting into.

### Primary issue

In the section 4 comments, "technical standards" aside, I think it is worth
emphasizing that things like what date-time format you use _are metadata_,
and one is better served by explicitly declaring your date format etc, even
if it is unusual, then by sticking to some convention like ISO8601 etc, but
not declaring it.  My original comment was meant primarily to highlight
that the issues in this section should be cast as metadata issues more than
standards issues.

### Minor issues

Even with EML, automatic integration of data isn't generally possible -- we
need semantics for that.  It does provide a way for a machine to check if
we forgot to provide the units of column 4 in the metadata.

Schemas like EML are stupidly hard to use at the moment, but I think that
is do to a lack of tools more than lack of training.  Any approach that
requires "not so simple steps to data sharing" is facing an uphill battle.
 your thoughts on this issue have inspired me though.  stay tuned for
https://github.com/ropensci/reml/ ;-)

On Wed, Jun 26, 2013 at 2:27 PM, Ethan White notifications@github.comwrote:

> @cboettig https://github.com/cboettig Having said all of this I have
> now tried to expand the metadata section just a bit to try to emphasize the
> value of this in #122https://github.com/weecology/data-sharing-paper/issues/122
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/weecology/data-sharing-paper/issues/71#issuecomment-20081437
> .

## 

Carl Boettiger
UC Santa Cruz
http://carlboettiger.info/

**Comment by ethanwhite** [comment]
> In the section 4 comments, "technical standards" aside, I think it is worth emphasizing that things like what date-time format you use _are metadata_, and one is better served by explicitly declaring your date format etc, even if it is unusual, then by sticking to some convention like ISO8601 etc, but not declaring it. My original comment was meant primarily to highlight that the issues in this section should be cast as metadata issues more than standards issues.

I finally got it. Thanks for clarifying once again. Yes, this should be documented as metadata and I've added a sentence to try to get the general point across (#123). It's a bit vague because the format = metadata argument certainly requires a bit of a higher level understanding to grock (if you and I were having a hard time communicating about it...).

> Even with EML, automatic integration of data isn't generally possible -- we need semantics for that. It does provide a way for a machine to check if we forgot to provide the units of column 4 in the metadata.

Yep, but I don't really see a way to communicate that level of subtly to this audience. I'm willing to sacrifice precision for communication here, but if you've got an idea for phrasing I'm certainly open to it.

>  Schemas like EML are stupidly hard to use at the moment, but I think that is do to a lack of tools more than lack of training. Any approach that requires "not so simple steps to data sharing" is facing an uphill battle. your thoughts on this issue have inspired me though. stay tuned for https://github.com/ropensci/reml/ ;-)

I so love the fact that our open dialogue about this manuscript has resulted in you starting a new R package. Open science FTW!

**Comment by jjhoyt** [comment]
@cboettig Hey Carl - thanks for the feedback that you did leave on PeerJ. I don't want to hijack the topic of this thread, but wanted to hear more from you about how you think the feedback could be improved. Email me if you can (to keep this thread on topic). FWIW - the 1500 char limit was considered a feature, not a bug, in an effort to keep feedback precise. And the thinking was that multiple concepts in feedback would be submitted separately as 1500 char or less 'chunks'. Admittedly, the UX is far from clear about this thinking.

**Comment by ethanwhite** [comment]
@cboettig I think I found a way to do a better job of being precise about metadata vs. semantics (see #129). Thanks again for all the great back and forth.
