### ISSUE TITLE
Reconsider whether (1) should just be in the introduction.

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#72]
Discussion from JE:

Dan Hocking:

> I felt like the first point on the importance of making your data available could just be
> part of the introduction, leaving you with 8 points. It’s really a matter of preference and 
> maybe it’s good to have as it’s own point to emphasize it since introductions often just get 
> skimmed. 

Ethan:

> Whether point 1 should be it’s own point or a part of the introduction was discussed several times. In the end we decided that it helped emphasize the importance of sharing data better to have it as its own point and that it helped us try to avoid discouraging people from sharing if the following recommendations seemed too difficult. That said, we’ll definitely go back and reconsider this again when revising.

**Comment by sarahsupp** [comment]
I still feel that the "why" for data sharing is important enough to have its own point. People do just skim introductions, and being its own point emphasizes why readers who may be ambivalent about data sharing should continue reading. Its true that this point is different in that it doesn't explain "how" to share your data, but it does explain "how" sharing your data benefits science.

**Comment by ethanwhite** [comment]
I agree.

**Comment by brymz** [comment]
Me, too.

**Comment by ethanwhite** [comment]
Alright, I'm going to go ahead and close this since we all agreed initially and at least most of us still feel the same way. Feel free to reopen if you've changed your mind.
