### ISSUE TITLE
Reconsider providing discussion of how to break up tables

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#73]
Discussion from JE:

Dan Hocking:

>  It might be good to provide a suggestion, even just a sentence, about how to break up tables. You mention linking tables (main field data with latitude, longitude, and weather/climate), but data can be broken up in a variety of ways. Does it make sense to have as much as possible in one table and only break thinks into related tables when otherwise impractical (or collected at different spatial/temporal scales than the primary data). For example, lat and long could be included next to each record or linked with another table so lat and long are just listed for each unique location. The later makes sense for lat and long but there are probably a lot of gray areas. Maybe it doesn’t matter as long as it’s well described in the metadata.

Ethan:

> We absolutely agree that this is an important point. The proper general rule from database normalization is to break things up as much as possible to avoid storing and entering duplicate information. So lat’s and long’s should be broken out into a sites table, taxonomic information should be broken out into a species table, etc. This was something we initially planned on adding to the format section and may have even had some text on, but decided that because not splitting things up didn’t really make it harder to reuse data in most cases that it was a level of complexity that we could afford to leave out. However, your comment has me rethinking this and we’ll definitely chat about whether it’s worth adding a few sentences to cover this.

**Comment by sarahsupp** [comment]
If we decided to add this point, it might fit well as a bullet point, since it is sort of a parallel concept to reducing duplication in data across columns - except in tables we are reducing duplication within tables by breaking information up by categorizing by data type (i.e., taxa, sites, etc.). "Ideally, tables should avoid storing duplicate information by dividing data into separate linked tables..." 
I'm on the fence on this one - it could be helpful, or it could complicate this section (because then we have to discuss new concepts related to linked tables, database managers).

**Comment by sarahsupp** [comment]
Actually, I just noticed that we reference linked tables in point 6. So maybe it does merit mentioning earlier in the ms..?

**Comment by embaldridge** [comment]
A researcher has to have the technical skills to actually link tables, so I think that makes this a more advanced skill.  However, it does save a lot of time on data entry to do good database normalization from the beginning, which is of major benefit to the data collector.

**Comment by brymz** [comment]
Could we mention what it is and why it is important and use a database
normalization/manager citation for the how?

**Comment by ethanwhite** [comment]
Group Discussion:

Can't figure out a way to do this without making things seem substantially more complicated, and it doesn't actually cause any meaningful problems to having anything in a single large table, so we're going to leave this out of this manuscript.
