### ISSUE TITLE
Mention that taxonomic information should be split into in separate columns

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#75]
From JE:

Dan Hocking:

> In point 6 it might be useful to state or diagram your recommended format for handling species names.

Ethan:

>  Another excellent point. Having spent a bit too much time parsing species names (with various levels of subspecies, hybrids, unknowns, etc.) out of single columns I really should have thought of that one. Consider it added!

**Comment by embaldridge** [comment]
A small figure, or in the text?

**Comment by brymz** [comment]
My sense is it will be fine in the text.

**Comment by ethanwhite** [comment]
I agree that in the text is the best way to go.
