### ISSUE TITLE
Null values should be easily distinguishable from the delimiter

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#76]
From JE:

Matt Davis:
Under “Use good null values” I would add that you should pick a null value that is easily distinguishable from the table delimiter. I have seen tab separated tables where the null value was a space…

**Comment by sarahsupp** [comment]
I think this is already in the text: "Note that a blank involves entering nothing, it is not a space, so if you use this option make sure there aren't any hidden spaces". Although we don't explicitly say that the problem could be that it is not distinguishable from the delimiter.

**Comment by embaldridge** [comment]
It is in the text, but it might add clarity if we added the delimiter thing.  One way that this issue could be addressed is to put space as a separate entry in the null values table, as I see that I left it out.
