### ISSUE TITLE
Add common issues/recommendations for GIS data

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#78]
From JE:

Thiago Silva:

> As a remote sensing/GIS/landscape ecology researcher, I am often faced with poorly reported location data, which can be a major source of desperation. These suggestions might be too narrow for you article, but feel free to use them if you’d like:
> 
> 1) PAY ATTENTION TO YOUR DATUM: the Datum is the theoretical, simplified 3-D representation of the surface of the Earth against which locations are determined. Every single geographical coordinate is measured in relation to a specific Datum, and if that information is omitted, you positional data is almost worthless. In this figure http://www.colorado.edu/geography/gcraft/notes/datum/gif/shift.gif, all points have the exact same coordinate, but notice how much their actual position changes if you change your reference (datum). It is nearly impossible to “guess” the datum for data that doesn’t have it reported, but is very easy to convert data between datums when needed, if the information is present.
> 
> So, make sure you know to which datum your GPS is set to, and make note of it in your field book and your metadata. If you don’t know which one to pick, use WGS-84 (BEFORE recording the locations, of course).
> 
> Later on, after you input the data into a GIS system, please don’t trust geospatial file formats (e.g. shapefiles) to carry on this information. Add a companion text file with metadata, and save yourself and others from future headaches.
> 
> Also note that datum != projection. A map projection is defined by the set of equations with which you take a set of coordinates measured against a 3d ellipsoidal shape (the datum), and redistribute them at relative positions on a plane, ideally preserving some properties of the original data (distances, angles, areas, etc). Changing projections does not change the coordinate values, only their relative position on the plane. But changing datums WILL change you coordinates, for the same geographic location.
> 
> 2) Precision: a lot of people prefer to use decimal degrees over degrees:minutes:seconds, as it is easier to input in a spreadsheet. If you do it, be VERY careful with rounding. For example, a degree of latitude/longitude is ~111 km at the Equator. So if you want a 10m precision (a realistic expectation for commercial handheld GPS receivers), you’ll need to record at least four decimal places. If you just write down 55.23º, you’re effectively rounding to the nearest km!
> 
> For this reason, I often recommend using UTM coordinates for everything that is sampled at a local scale. UTM units are given in meters, not degrees, so by writing the full number you’re always sure you have enough precision. As a bonus, UTM coordinates are by convention always measured relative to the WGS84 datum, so you kill two birds with one stone.
> 
> 3) Reporting: if you don’t like UTM coordinates (or your study site is unfortunately spread across two UTM zones), and you want to play safe, you’ll write your coordinates in the field as DDº MM’ SS.S” (and make note of the datum!). This notation, however, is unintelligible for pretty much any software, unless you use string parsing. A much better way to report is to have separate columns in your data table, such as lat_deg, lat_min, lat_sec, lon_deg, lon_min, lon_sec. And don’t forget to use negative signs on the degree column, to indicate southern/western hemispheres (instead of N,S,W,E). If you have the data organized like this, you can easily convert it to decimal degrees before feeding it to a GIS or statistical package, using dec_lat = lat_deg + (lat_min/60) + (lat_sec/3600), and the software will give you all the decimal places that you could ever want. No precision lost.

Ethan:

> Getting into the specific issues of spatial data was another thing we went back and forth about and decided to leave out, but your comment has reminded me of how common an issue this is and it’s important consequences. I think that with a couple of additional sentences in Section 6 we should be able to include the basic message. Do you have a particularly good introductory level citation that you recommend for these issues.

Thiago:

> Can’t think of an easy, accessible reference, from the top of my head. Which is probably part of the problem; explanations of these concepts are buried in GIS and Cartography books, and usually are not approached at all in Ecology textbooks, leading to the assumption that geographic coordinates are unique, immutable units.
> 
> I particularly like this book, though: http://goo.gl/w1AWC . It’s cheap, short, and easy to understand, and covers datums, projection, geoids, and the GPS system. It should be on the reference shelf of any lab that acquires spatial data.

**Comment by sarahsupp** [comment]
Some possible references: Hook et al. 2010 - http://im.lternet.edu/sites/im.lternet.edu/files/BestPractices-2010.pdf
Hook et al. recommend (p 7, Appendix A & C) that spatial coordinates be reported in decimal degrees to at least 4 significant digits past the decimal point (but preferably 5-6). They also reminds people to make sure that S and W coordinates are negative (a common error!).  NOTE: We share some recommendations, but other recommendations are ones that we strongly disagree with in this paper (i.e. using -9999 as a null value). This paper is really long - I've only just scanned it.

Cook et al. 2001 (Bulletin of the Ecological Society of America) make the same spatial data recommendations, with the same contradiction that -999 is an OK null value... - http://www.jstor.org.dist.lib.usu.edu/stable/pdfplus/20168543.pdf?acceptTC=true

**Comment by ethanwhite** [comment]
Group Discussion:

Add to Section 6 (linking to other datasets).

**Comment by embaldridge** [comment]
That makes sense.

**Comment by brymz** [comment]
See pull request (#116)

**Comment by ethanwhite** [comment]
Reopening until #116 is merged.
