### ISSUE TITLE
Consider mentioning re3data.org and/or other repository search sites

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#82]
Heinz Pampel (from PeerJ comments):

> The re3data.org (http://re3data.org) registry makes it possible to identify an appropriate data repository. A system of icons helps users to identify a suitable repository for the storage of their data.

**Comment by strasser** [comment]
Also [databib.org](http://databib.org). Not sure how much overlap there is between repos with re3data.org.
