### ISSUE TITLE
Reviewer/editor comments

### ISSUE THREAD

**Issue by karthik** [weecology/data-sharing-paper#83]
Ethan White and colleagues present an extremely useful review on practical steps towards data sharing. At a time when **data revolution** and the **4th paradigm** are topics du jour in many scientific circles, the tone and nature of discussions seem to ignore the fact that many researchers exist outside the bubble. This article also provides a much needed update to suggestions presented in Borer 2009.
## comments
- [ ] 1. Clarify the target audience

Although the title of the article is quite broad and some guidelines are general enough to be applicable to any research community, the article is clearly geared towards environmental scientists. More specifically, the repositories suggested in the article are all associated with EEB (and closely related) journals and communities. Also the guidelines for preparing data are also limited to basic tabular data (and do not cover other  heterogeneous and large data types which are characteristic of communities such as astronomy and physics). I don't make the last point as a criticism or to suggest that the review is not comprehensive. Instead I'm suggesting that clarifying the audience both in the title and early in the introduction could provide some additional focus.
- [ ] 2. logistical versus technical?  

When you say logistical do you actually mean technical? A vast majority of researchers still use GUI tools and manipulate most of their data by hand. This subset of researchers also lack the technical skills necessary to prepare and submit their data to a repository. So to me this seems more of a technical than (a bit of both really) a logistical challenge. 
- [ ] 3. Sections 3-5: 

I recommend skimming Michener and Jones 2012 for additional points to share in this context (see citation at the bottom). Steps `3`, `4` and parts of `5` from the review have several additional useful suggestions for someone preparing their data for sharing purposes. In particular, it would be worth noting that:

a) Storing data in relational databases can better ensure that multiple data types don't get mixed up in the same column (which as you point out is much more common problem in programs like Excel).

b) The Michener/Jones section on metadata (also see the part titled _assure_) contains some additional information that also applies to the QA/QC section. 

Given that ecological experiments rarely go exactly as planned, and data can be messy, researchers should strive to describe the circumstances as accurately as possible so future consumers can best decide if the data can be integrated into a new study. The most common scenario is that detailed metadata are missing which means that a careful downstream consumer will have to discard the data rather than use one they do not fully trust. This bit seems implied rather than explicitly pointed in the metadata section.
- [ ] 4. QA/QC  

In addition to just giving the data a once over before sharing, there are a couple of other useful suggestions that might be worth sharing in this section:

Trusting someone else's data is often very hard for downstream consumers (There is some interesting discussion in Zimmerman 2008). So if people can provide additional flags or indicators about the data quality (not QA), that could help lower the barrier to reuse. Obviously this is suggestion may not apply to certain types of data. 

When taking about sanity checks, it might also be worth mentioning that the same steps could be done programmatically. For example, in R one can use `melt` and `cast` to actually figure out if there are any missing measurements without manually scanning spreadsheets. Mentioning this a second time (in addition to the R/Python Pandas mention) might actually help nudge readers towards better scientific computing practices (although any discussion on this matter is well outside the scope of this article).
- [ ] 5. Citation suggestion  

In section #8, it might be worth citing Schultheiss (2011) where they quantitatively show that data stored on lab computers and web pages disappear often.
- [ ] 6. figshare  

Many of the repositories mentioned in this section are specific to certain data types (e.g. Genbank) or require a paper be associated with a publication in a member journal (e.g. Dryad). I noticed that although you mentioned figshare in that table you don't actually say that it's the easiest and fastest option available in table 2. This would be really helpful for readers in communities where there is no data sharing culture whatsoever (so they can't really follow their peers) or rely on institutional support (like what DataUP provides for the UC). 

**Figshare** should be **figshare**. They do not capitalize their name.
# Refs mentioned above

Schultheiss, S.J., Münch, M.-C., Andreeva, G.D. & Rätsch, G. (2011). Persistence and availability of Web services in computational biology. PloS one, 6, e24914.

Michener, W.K. & Jones, M.B. (2012). Ecoinformatics: supporting ecology as a data-intensive science. Trends in Ecology & Evolution, 27, 85–93.

Zimmerman, A.S. (2008). New Knowledge from Old Data: The Role of Standards in the Sharing and Reuse of Ecological Data. Science, Technology & Human Values, 33, 631–652.

**Comment by ethanwhite** [comment]
Broken out in #84 - #91.
