### ISSUE TITLE
"Logistical" vs. "Technical"

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#85]
Karthik Ram (#83):

> When you say logistical do you actually mean technical? A vast majority of researchers still use GUI tools and manipulate most of their data by hand. This subset of researchers also lack the technical skills necessary to prepare and submit their data to a repository. So to me this seems more of a technical than (a bit of both really) a logistical challenge.

**Comment by ethanwhite** [comment]
Group Discussion:

Sounds good, let's change it. There may be a more generic term that could work as well.

**Comment by embaldridge** [comment]
Fixed.
