### ISSUE TITLE
Suggestions for sections 3-5

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#86]
Karthik Ram (#83):

> I recommend skimming Michener and Jones 2012 for additional points to share in this context (see citation at the bottom). Steps 3, 4 and parts of 5 from the review have several additional useful suggestions for someone preparing their data for sharing purposes. In particular, it would be worth noting that:
> 
> a) Storing data in relational databases can better ensure that multiple data types don't get mixed up in the same column (which as you point out is much more common problem in programs like Excel).
> 
> b) The Michener/Jones section on metadata (also see the part titled assure) contains some additional information that also applies to the QA/QC section.
> 
> Given that ecological experiments rarely go exactly as planned, and data can be messy, researchers should strive to describe the circumstances as accurately as possible so future consumers can best decide if the data can be integrated into a new study. The most common scenario is that detailed metadata are missing which means that a careful downstream consumer will have to discard the data rather than use one they do not fully trust. This bit seems implied rather than explicitly pointed in the metadata section.
> 
> Michener, W.K. & Jones, M.B. (2012). Ecoinformatics: supporting ecology as a data-intensive science. Trends in Ecology & Evolution, 27, 85–93.

**Comment by sarahsupp** [comment]
We should def. add this reference to our paper.

a) again suggests that we should address linked tables (and relational databases) as earlier comments suggested - Section 4.

b) Michener describes two forms of quality control: Before (assigning and defining) and After (error checking and sanity checks). I like this idea that an important part of QA/QC is having a good data collection and management plan before beginning.

**Comment by ethanwhite** [comment]
Group Discussion:

a) seems too advanced for the paper since we don't talk about relational structures. Some of this is already mentioned in a general way in Section 7.

b) add something along these lines to either the QA/QC section or the concluding remarks. Basically thinking about the ideas in this paper _before_ you start collecting and entering data can save you a lot of time.
