### ISSUE TITLE
Flags for data quality

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#87]
Karthik Ram (#83):

> Trusting someone else's data is often very hard for downstream consumers (There is some interesting discussion in Zimmerman 2008). So if people can provide additional flags or indicators about the data quality (not QA), that could help lower the barrier to reuse. Obviously this is suggestion may not apply to certain types of data. 
> 
> Zimmerman, A.S. (2008). New Knowledge from Old Data: The Role of Standards in the Sharing and Reuse of Ecological Data. Science, Technology & Human Values, 33, 631–652.

**Comment by sarahsupp** [comment]
This citation could fit under point #4 in the metadata section.

**Comment by ethanwhite** [comment]
Group discussion:

Do what Sarah said.
