### ISSUE TITLE
Programmatic sanity checks

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#88]
Karthik Ram (#83):

> When taking about sanity checks, it might also be worth mentioning that the same steps could be done programmatically. For example, in R one can use melt and cast to actually figure out if there are any missing measurements without manually scanning spreadsheets. Mentioning this a second time (in addition to the R/Python Pandas mention) might actually help nudge readers towards better scientific computing practices (although any discussion on this matter is well outside the scope of this article).

Carl Boettiger (#71):

> Very good section, but you ignore any mention of tools that can assist with at least some of these things, from the very basic (e.g. reading the file into software such as R and performing basic visual inspection / graphing to make sure it is imported) to richer options possible with stricter formats (XML schema validation, etc.). 

Since both Karthik and Carl highlight this we should add at least a sentence or two, but we need to avoid getting into the technical details too much given the target audience. I definitely think that getting into XML schema validation is way too advanced.

**Comment by embaldridge** [comment]
I agree.

**Comment by sarahsupp** [comment]
"More advanced quality control can include automated checks on data as it is entered and double-entry of data [@lampe1998; @paulsen2012] or programmatic checks using software tools such as R or Python."

**Comment by ethanwhite** [comment]
That covers the data entry side of things, but I think they are more interested in the _post hoc_ tests. I'll offer a one line suggestion for addressing this momentarily.
