### ISSUE TITLE
Add citation for loss of data on lab computers and web pages

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#89]
Karthik Ram (#83):

> In section #8, it might be worth citing Schultheiss (2011) where they quantitatively show that data stored on lab computers and web pages disappear often.
> 
> Schultheiss, S.J., Münch, M.-C., Andreeva, G.D. & Rätsch, G. (2011). Persistence and availability of Web services in computational biology. PloS one, 6, e24914.

**Comment by ethanwhite** [comment]
@karthikram - I'd certainly love to have a citation for this, but this seems to be about web services for analysis, not datasets. I have no doubt that the results extrapolate, but it seems like a little bit of a stretch for citation in the current paper. Am I missing something?

**Comment by karthik** [comment]
Good point. Perhaps not the best suggestion so please ignore.

**Comment by ethanwhite** [comment]
Thanks. I love being able to actively converse with reviewers rather than having the disjointed communication of typically review.

**Comment by karthik** [comment]
Agreed. If there is anything else I can clarify please continue to bug me.
