### ISSUE TITLE
Stronger recommendation for figshare?

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#90]
Karthik Ram (#83):

> Many of the repositories mentioned in this section are specific to certain data types (e.g. Genbank) or require a paper be associated with a publication in a member journal (e.g. Dryad). I noticed that although you mentioned figshare in that table you don't actually say that it's the easiest and fastest option available in table 2. This would be really helpful for readers in communities where there is no data sharing culture whatsoever (so they can't really follow their peers) or rely on institutional support (like what DataUP provides for the UC).

**Comment by sarahsupp** [comment]
We already state that "data of any kind can be shared" on figshare. I'm not sure we should have a strong role in the paper pushing people toward one repository over another.

**Comment by ethanwhite** [comment]
I generally agree. We could add the word easily, "data of any kind can easily be shared", to emphasize the point that it can be easy to share any kind of data through some outlets, which is definitely an important point.

**Comment by ethanwhite** [comment]
Group Discussion:

General agreement with above comments.
