### ISSUE TITLE
Revisit the lack of emphasis on machine readable metadata

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#93]
Carl Boettiger (#71):

> L 82-84. Like much other advice, you casually throw out names of "metadata standards", some of which are defined as XML Schema, some of which are vocabularies or proper ontologies, etc., along side vague recommendations to "describe the data". My intuition is that the average ecologist reading this will go through these recommendations like this:
> 
> 1) Describe the "What, when, where, how of the data" -- oh, that'll be in the published paper.
> 2) "How to access the data" email me, duh. I'm the corresponding author. It says so on the paper.
> 3) "Suitability of the data in answering other questions" Stuff I'll probably discuss in the introduction. If you don't know what it's suitable for, you probably shouldn't be using my data anyhow.
> 4) "Warnings about known problems" You kidding me? My data does not have problems or inconsistencies!
> 5) "Information to confirm that the data is properly imported, like the number of rows and columns". Ah ha! What a good idea, I'll list the number of rows and columns of my data and I'll be cutting edge.
> 
> If we are serious about improving ecological metadata, I think we need something more persuasive about how it can add value and to whom. The current manuscript makes no attempt to explain the value of machine readable standards (even merely to point out they are machine-readable). Yes, you point to three excellent tools which helping to lower the technical barrier, but not the social / motivational barriers.
> 
> Also, there's a lot of overlap here with the issues in #4 "Standard data formats", but the link is not made clear. 

We've discussed the tradeoffs of pushing machine readable metadata extensively, and this is exactly the response I expected from folks with the ability to actively benefit from machine readable metadata. That said, it's worth revisiting one more time given the value of the approach even if it is largely inaccessible to the average ecologist.

I'm personally a bit unclear regarding the overlap with section 4.

**Comment by embaldridge** [comment]
I think that the creation of machine readable metadata to the novice data manager is another barrier to sharing data, even with the tools available.  I think it is worth mentioning that it is exists, but is a more advanced area of data sharing.   Perhaps rearranging the section slightly would add clarity.  I think we may also be having a problem with the language that we are using to describe metadata.  Making a distinction between practices for creating good metadata ( the information neccessary) and metadata standards (machine readable) might help clarify this issue.

**Comment by sarahsupp** [comment]
I tend to agree with Elita here. We can make the language more clear about why machine readable metadata is important and useful, but I hesitate to add more technical complexity to the main point.

**Comment by brymz** [comment]
Yes, we've emphasized the "easy." Do we have a better sense of the other
papers in the issue? Maybe we can refer to another more technically driven
article.
