### ISSUE TITLE
Standard data formats are addressed by metadata standards

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#95]
Carl Boettiger (#71):

> My only gripe is that a lot of the issues discussed here are addressed by the metadata standards you cite earlier, but the connection is completely ignored and probably lost on most readers. 

We should confirm this (I'm sure Carl is right, I'm just not familiar with that aspect of the standards) and then add a sentence indicating this.

**Comment by ethanwhite** [comment]
Group Discussion:

General feeling is that this level of connection will be uninteresting to and lost on most of our target audience even if we make it, but let's contact Carl and get some feedback about what exactly he thinks should be added.

**Comment by dmcglinn** [comment]
I contacted @cboettig via email.

**Comment by ethanwhite** [comment]
Based on our conversation and the dialogue with Carl in #71 I think this can probably be closed, but if someone has an idea of gently introducing this idea they should go for it.
