### ISSUE TITLE
Add mention of archiving data related code

### ISSUE THREAD

**Issue by ethanwhite** [weecology/data-sharing-paper#98]
Carl Boettiger (#71):

> Could you consider mentioning archiving things like an R script that is used to clean / manipulate the raw data to prepare it for analysis as well? 

We had this in the ms at one point, but I guess we took it out for brevity/clarity? We should look to see if it will go back in smoothly.

**Comment by ethanwhite** [comment]
Group Discussion:

Already in the raw data section. Add a mention of "(and associated code)" to the opening sentence or two of the repo section.

**Comment by klocey** [comment]
I did exactly that (added to 2nd sentence). There are several other places where "and code" could be added in the repo section, but doing so opens up a brand new 'can of worms'. I think it's good that we mention it briefly in the repo section and then keep the emphasis on data.
